### ISSUE TITLE
Unable to export with shaders on v1.2

### ISSUE THREAD

**Issue by MDashK** [KuromeSan/GayMaker-Studio#1]
v1.2 is unable to export games with shaders, gives out the error of "no rooms found in project".

**Comment by MDashK** [comment]
The issue is in the "GayMakerStudio.cs" file, the argument output for shaders has an extra space in the ps4sdk option.
It should be "/ps4sdk=", but it's "/ ps4sdk=", hence why the GM compiler errors out when used with shaders.

**Comment by LiEnby** [comment]
i fixed it but apparently i cant build this using xbuild on linux, idk why um

**Comment by LiEnby** [comment]
fixed
